# Generated by Django 4.2.2 on 2023-08-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=100),
        ),
    ]
