# Generated by Django 4.2.2 on 2023-06-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_customuser_user_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.roles'),
        ),
    ]
