# Generated by Django 4.2.2 on 2023-08-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(default='2', max_length=100),
        ),
    ]
