# Generated by Django 4.2.2 on 2023-08-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='static/profilepic/default_profile.png', null=True, upload_to='static/profilepic'),
        ),
    ]
