# Generated by Django 4.2.2 on 2023-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_cuisine_calculated_rating_id_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(null=True, upload_to='static/category/'),
        ),
    ]
