# Generated by Django 4.2.2 on 2023-06-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminuser', '0005_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('youtube_link', models.CharField(max_length=255, null=True)),
                ('dateModified', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDescription_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dateModified',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Approval',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoryRecipe', to='adminuser.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calculated_rating_id',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='idMeal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userRecipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reports',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipeReports', to='adminuser.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Recipe_Ingredient',
        ),
        migrations.AddField(
            model_name='recipedescription_ingredient',
            name='Ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientRecipeDescription_Ingredient', to='adminuser.ingredient'),
        ),
        migrations.AddField(
            model_name='recipedescription_ingredient',
            name='recipeDescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipeDescriptionRecipeDescription_Ingredient', to='adminuser.recipedescription'),
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipeRecipeDescription', to='adminuser.recipe'),
        ),
        migrations.AddField(
            model_name='recipedescription',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminuser.recipe'),
        ),
        migrations.AddField(
            model_name='rating',
            name='recipeDescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipeDescriptionRating', to='adminuser.recipedescription'),
        ),
    ]
