# Generated by Django 4.2.2 on 2023-06-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0006_recipedescription_recipedescription_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='calculated_rating_id',
            new_name='calculated_rating',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Approval',
            new_name='is_approved',
        ),
    ]
