# Generated by Django 4.2.2 on 2023-06-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0008_rename_category_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedescription',
            name='thumbnail',
        ),
    ]
