# Generated by Django 4.2.2 on 2023-07-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0011_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
