# Generated by Django 4.2.2 on 2023-07-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0013_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
