# Generated by Django 4.2.2 on 2023-07-07 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminuser', '0015_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rating', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
