# Generated by Django 4.2.2 on 2023-07-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0016_remove_rating_user_rating_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='userid',
            new_name='user',
        ),
    ]
