# Generated by Django 4.2.2 on 2023-07-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0018_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='ingredient',
            new_name='user',
        ),
    ]
