# Generated by Django 4.2.2 on 2023-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0019_rename_ingredient_favourites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id_ingrediant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
