# Generated by Django 4.2.2 on 2023-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0020_recipe_is_active_alter_ingredient_id_ingrediant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='static/ingredients/'),
        ),
    ]
