# Generated by Django 4.2.2 on 2023-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0022_request_status_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
