# Generated by Django 4.2.2 on 2023-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0023_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
