# Generated by Django 4.2.2 on 2023-07-19 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0024_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='my_date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
