# Generated by Django 4.2.2 on 2023-07-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0025_request_my_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='my_date_field',
            new_name='creation_date',
        ),
    ]
