# Generated by Django 4.2.2 on 2023-07-26 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminuser', '0028_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentslike', to='adminuser.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentslike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsdislike', to='adminuser.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsdislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
